### ISSUE TITLE
User Story: Make managing time more fun

### ISSUE THREAD

**Issue by unsatisfiedpopcorn** [CS2103-AY1819S1-F11-3/main#3] opened 2018-09-03 14:47 UTC
As a student with close to zero daily motivation, I want to make managing my time more fun, so that I can put my affairs in order with less pain.

**Comment by pengnam** [comment] 2018-09-18 12:10
Duplicate of #7 . Hence, I have closed this issue.

**Closed by pengnam** 2018-09-18 12:10 UTC
Labels: priority.Nice-To-Have, type.Story
